<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVbxxC48\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVbxxC48/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVbxxC48.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVbxxC48\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVbxxC48\App_KernelDevDebugContainer([
    'container.build_hash' => 'VbxxC48',
    'container.build_id' => 'b71f8ecb',
    'container.build_time' => 1717682481,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVbxxC48');
