<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVE8MOUz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVE8MOUz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVE8MOUz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVE8MOUz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVE8MOUz\App_KernelDevDebugContainer([
    'container.build_hash' => 'VE8MOUz',
    'container.build_id' => '5f3e6f63',
    'container.build_time' => 1717596419,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVE8MOUz');
