<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC2Ij1xp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2Ij1xp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC2Ij1xp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC2Ij1xp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC2Ij1xp\App_KernelDevDebugContainer([
    'container.build_hash' => 'C2Ij1xp',
    'container.build_id' => '62af07bd',
    'container.build_time' => 1717691585,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2Ij1xp');
